### ISSUE TITLE
Current Todo

### ISSUE THREAD

**Issue by cookie777** [cookie777/landing-page-foreach-item#3]
- [ ] add each section
- [ ] pass image path
- [ ] create components to reduce repetitive div
- [ ] gather all imgaURL and text data in data.js
- [ ] iterate and pass those data into component
